CREATE TABLE `slider_inicio` ( `id` INT NOT NULL AUTO_INCREMENT , `imagen` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,  `titulo` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `texto` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `orden` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL , `pagina_inicio_id` INT NOT NULL , PRIMARY KEY (`id`), INDEX (`pagina_inicio_id`)) ENGINE = InnoDB;

CREATE TABLE `slider_quienes_somos` ( `id` INT NOT NULL AUTO_INCREMENT , `imagen` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,  `titulo` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `texto` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `orden` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `quienes_somos_id` INT NOT NULL ,    PRIMARY KEY  (`id`), INDEX (`quienes_somos_id`)) ENGINE = InnoDB;

CREATE TABLE `slider_produccion` ( `id` INT NOT NULL AUTO_INCREMENT ,  `imagen` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,  `titulo` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `texto` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `orden` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `produccion_id` INT NOT NULL ,    PRIMARY KEY  (`id`),    INDEX  (`produccion_id`)) ENGINE = InnoDB;

CREATE TABLE `slider_exportacion` ( `id` INT NOT NULL AUTO_INCREMENT ,  `imagen` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,  `titulo` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `texto` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `orden` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `exportacion_id` INT NOT NULL ,    PRIMARY KEY  (`id`),    INDEX  (`exportacion_id`)) ENGINE = InnoDB;

CREATE TABLE `slider_productos` ( `id` INT NOT NULL AUTO_INCREMENT ,  `imagen` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,  `titulo` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `texto` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `orden` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `pagina_productos_id` INT NOT NULL ,    PRIMARY KEY  (`id`),    INDEX  (`pagina_productos_id`)) ENGINE = InnoDB;

CREATE TABLE `slider_calidad` ( `id` INT NOT NULL AUTO_INCREMENT ,  `imagen` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,  `titulo` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `texto` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `orden` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `calidad_id` INT NOT NULL ,    PRIMARY KEY  (`id`),    INDEX  (`calidad_id`)) ENGINE = InnoDB;

CREATE TABLE `slider_impacto_social` ( `id` INT NOT NULL AUTO_INCREMENT ,  `imagen` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,  `titulo` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `texto` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `orden` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `impacto_social_id` INT NOT NULL ,    PRIMARY KEY  (`id`),    INDEX  (`impacto_social_id`)) ENGINE = InnoDB;

CREATE TABLE `slider_recursos_humanos` ( `id` INT NOT NULL AUTO_INCREMENT ,  `imagen` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,  `titulo` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `texto` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `orden` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `pagina_recursos_humanos_id` INT NOT NULL ,    PRIMARY KEY  (`id`),    INDEX  (`pagina_recursos_humanos_id`)) ENGINE = InnoDB;

CREATE TABLE `slider_contacto` ( `id` INT NOT NULL AUTO_INCREMENT ,  `imagen` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,  `titulo` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `texto` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `orden` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,  `pagina_contacto_id` INT NOT NULL ,    PRIMARY KEY  (`id`),    INDEX  (`pagina_contacto_id`)) ENGINE = InnoDB;




ALTER TABLE `corte` CHANGE `nombre` `nombre` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `descripcion` `descripcion` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `tamano_caja` `tamano_caja` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `medidas` `medidas` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `envasado` `envasado` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `piezas_por_caja` `piezas_por_caja` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `condiciones_termicas` `condiciones_termicas` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `especificaciones` `especificaciones` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;